### ISSUE TITLE
Karma counts should be local

### ISSUE THREAD

**Issue by dekarrin** [moe-serifu-circle/masabot#6]
Currently, karma is tracked across all servers that MasaBot is in. It's okay to have global karma, but there should be local karma as well.

A/C: Make karma tracking be local to a server by default. Also track the global karma, but make the server-specific karma show up by default. A new command or option to the existing command can be given to show the global karma count.

**Comment by Shensd** [comment]
Made a pull request for this issue at https://github.com/moe-serifu-circle/masabot/pull/7
